// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUggLeBWL1Mn-xdUuBx_WEHpAd8YdlH_8',
    appId: '1:429634223536:android:41b8b4f080c99acaa6ea75',
    messagingSenderId: '429634223536',
    projectId: 'jadifit-8477a',
    storageBucket: 'jadifit-8477a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpv_xEH5VAj_uFxEeg5KJt0BPWhiamJM',
    appId: '1:429634223536:ios:d5fb82a4ef4dc3eaa6ea75',
    messagingSenderId: '429634223536',
    projectId: 'jadifit-8477a',
    storageBucket: 'jadifit-8477a.firebasestorage.app',
    iosBundleId: 'com.example.googleHackathon',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPvKunZN-fxZAyTa_R7k0usGaxE207vU',
    appId: '1:429634223536:web:9dda7d1891851482a6ea75',
    messagingSenderId: '429634223536',
    projectId: 'jadifit-8477a',
    authDomain: 'jadifit-8477a.firebaseapp.com',
    storageBucket: 'jadifit-8477a.firebasestorage.app',
    measurementId: 'G-5MP6JWJ1QH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpv_xEH5VAj_uFxEeg5KJt0BPWhiamJM',
    appId: '1:429634223536:ios:d5fb82a4ef4dc3eaa6ea75',
    messagingSenderId: '429634223536',
    projectId: 'jadifit-8477a',
    storageBucket: 'jadifit-8477a.firebasestorage.app',
    iosBundleId: 'com.example.googleHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPvKunZN-fxZAyTa_R7k0usGaxE207vU',
    appId: '1:429634223536:web:29056c55fbf7df61a6ea75',
    messagingSenderId: '429634223536',
    projectId: 'jadifit-8477a',
    authDomain: 'jadifit-8477a.firebaseapp.com',
    storageBucket: 'jadifit-8477a.firebasestorage.app',
    measurementId: 'G-GN4RKCV6V5',
  );

}